// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qedbeipfgcaehzgltvuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZGJlaXBmZ2NhZWh6Z2x0dnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTkwOTEsImV4cCI6MjA3NDM5NTA5MX0.C0z5PgGBN6eiMOvjhH0cCIzqkonwJdI_RgJ9jEUkmsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});